// String name = 'undefined',
//     String description = '',
// double price = 0.0,
//     double doubleweight = 0.0,
// int quantity = 0,
//     String category = 'undefined',
// String? unit = 'apples',
//     double discountPercent = 0.0,
// int minimumOrderQuantity = 1,
//     int stockLevel = 0,
// bool isAvailable = true,
//     String? imageUrl,